### ISSUE TITLE
Prevent duplicates?

### ISSUE THREAD

**Issue by aulneau** [davibe/next.js-example-with-global-stylesheet#5]
Hello!

Would it be possible to prevent duplicate styles from being injected?

For example, let's say I have a `content-section` component and I use it 7 times on a page, it would be great if we could only include the first `<style>` that is included in the component. Similar to what `styled jsx` does.

**Comment by danielantelo** [comment]
+1

**Comment by davibe** [comment]
The reason why this plugin is called `global` is because it should be used to include one or more styles in the page (root) component, once. Something similar to what existing projects (non component-based) and designers are used to.

Using this plugin inside reusable components makes slighy less sense as it leads to naming conflicts and maybe other problems i am not aware of.. If you're doing that you should think about using styled jsx imho.

**Comment by aulneau** [comment]
@davibe, i hear you.

Part of the issue is that caused me to bring this up is that I don't think you can get the same or similar env for writing styles in js (such as styled jsx, or styled jsx postcss) as you get innately scss.

I spent the last few days trying to recreate what I have by default in sass with the aforementioned libs and it just feels too early, conflicts and other issues came up. I 100% seeing being able to leverage things like polished, glamor and all the postcss plugins to create an env that is the same or better than scss, but I just don't know if it's possible right now.

I really don't know what would be involved in de-duping the injected styles for this, but I thought it could be a good middle-ground while we wait for the space to grow a bit.

**Comment by davibe** [comment]
As of now you're forced to pick a compromise between limited scoped style and full-featured global styles depending on what you are doing. More powerful scoped styles are being worked on but it's a complex matter and it's out of the scope of this example.

You can try to follow the issues on next.js / styled-jsx and join the zeit-community slack channel if you have not done it yet.

**Comment by aulneau** [comment]
Thanks @davibe!
